import sys
import os
import json
from neo4j import GraphDatabase

# --- AURA DB CONNECTION SETTINGS ---
URI = "bolt+ssc://a7c4fec6.databases.neo4j.io" 
USER = "neo4j"
PASS = "pUTM7SqI9HE6H8awExoZK2PKEHznG2sIMFYEaibOwY8" 

# --- OUTPUT SETTINGS ---
OUTPUT_DIR = "remediation_fixes"
TF_FILE = os.path.join(OUTPUT_DIR, "least_privilege_fix.tf")
ALERT_FILE = os.path.join(OUTPUT_DIR, "high_risk_alerts.json")

def analyze_and_remediate():
    print(f"[*] [Stage 5] Connecting to Graph Engine to analyze risks: {URI}...")
    driver = GraphDatabase.driver(URI, auth=(USER, PASS))
    
    # Ensure our output directory exists
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    risky_assignments = []

    try:
        driver.verify_connectivity()
        
        with driver.session() as session:
            # Cypher Query: Find any Principal assigned a highly dangerous Azure Role
            print("[*] Running escalation path finder query...")
            query = """
            MATCH (p:Principal)-[a:ASSIGNED]->(r:Role)
            WHERE r.name IN ['Owner', 'Global Administrator', 'User Access Administrator']
            RETURN p.id AS principal_id, r.name AS role_name, a.scope AS scope
            """
            
            result = session.run(query)
            for record in result:
                risky_assignments.append({
                    "principal_id": record["principal_id"],
                    "role_name": record["role_name"],
                    "scope": record["scope"]
                })
                
        if not risky_assignments:
            print("[+] No high-risk Azure role assignments found. Cloud environment is secure.")
            sys.exit(0)
            
        print(f"[!] Found {len(risky_assignments)} high-risk assignments. Generating remediation code...")
        
        # 1. Generate JSON Alerts (for Jira/Email ticketing)
        with open(ALERT_FILE, 'w') as f:
            json.dump(risky_assignments, f, indent=4)
            
        # 2. Generate Terraform Policy-as-Code Fixes (Least Privilege)
        with open(TF_FILE, 'w') as f:
            f.write("# AUTOMATED REMEDIATION ENGINE FIXES\n")
            f.write("# Generated by Cloud Risk Engine\n\n")
            
            for i, risk in enumerate(risky_assignments):
                # Suggesting a downgrade from Owner/Admin to 'Reader'
                f.write(f"// REMEDIATION: Downgrading {risk['principal_id']} from {risk['role_name']} to Reader\n")
                f.write(f"resource \"azurerm_role_assignment\" \"remediation_fix_{i}\" {{\n")
                f.write(f"  principal_id         = \"{risk['principal_id']}\"\n")
                f.write(f"  role_definition_name = \"Reader\" # Downgraded for Least Privilege\n")
                f.write(f"  scope                = \"{risk['scope']}\"\n")
                f.write("}\n\n")
                
        print(f"[+] Remediation artifacts generated successfully in: {OUTPUT_DIR}/")
        
    except Exception as e:
        print(f"[-] FATAL ERROR: {e}")
        sys.exit(1)
    finally:
        driver.close()

if __name__ == "__main__":
    analyze_and_remediate()
